-- Full ISO 3166-1 country list for dropdowns
DELETE FROM community_regions;
DELETE FROM community_countries;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AF', 'Afghanistan', 101) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AX', 'Åland Islands', 102) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AL', 'Albania', 103) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('DZ', 'Algeria', 104) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AS', 'American Samoa', 105) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AD', 'Andorra', 106) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AO', 'Angola', 107) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AI', 'Anguilla', 108) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AQ', 'Antarctica', 109) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AG', 'Antigua and Barbuda', 110) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AR', 'Argentina', 111) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AM', 'Armenia', 112) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AW', 'Aruba', 113) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AU', 'Australia', 114) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AT', 'Austria', 115) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AZ', 'Azerbaijan', 116) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BS', 'Bahamas', 117) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BH', 'Bahrain', 118) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BD', 'Bangladesh', 119) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BB', 'Barbados', 120) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BY', 'Belarus', 121) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BE', 'Belgium', 122) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BZ', 'Belize', 123) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BJ', 'Benin', 124) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BM', 'Bermuda', 125) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BT', 'Bhutan', 126) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BO', 'Bolivia', 127) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BQ', 'Bonaire, Sint Eustatius and Saba', 128) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BA', 'Bosnia and Herzegovina', 129) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BW', 'Botswana', 130) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BV', 'Bouvet Island', 131) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BR', 'Brazil', 132) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('IO', 'British Indian Ocean Territory', 133) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BN', 'Brunei Darussalam', 134) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BG', 'Bulgaria', 135) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BF', 'Burkina Faso', 136) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BI', 'Burundi', 137) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CV', 'Cabo Verde', 138) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('KH', 'Cambodia', 139) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CM', 'Cameroon', 140) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CA', 'Canada', 7) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('KY', 'Cayman Islands', 142) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CF', 'Central African Republic', 143) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TD', 'Chad', 144) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CL', 'Chile', 145) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CN', 'China', 146) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CX', 'Christmas Island', 147) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CC', 'Cocos (Keeling) Islands', 148) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CO', 'Colombia', 149) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('KM', 'Comoros', 150) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CG', 'Congo', 151) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CD', 'Congo, Democratic Republic of the', 152) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CK', 'Cook Islands', 153) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CR', 'Costa Rica', 154) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CI', 'Côte d''Ivoire', 155) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('HR', 'Croatia', 156) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CU', 'Cuba', 157) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CW', 'Curaçao', 158) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CY', 'Cyprus', 159) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CZ', 'Czechia', 160) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('DK', 'Denmark', 161) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('DJ', 'Djibouti', 162) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('DM', 'Dominica', 163) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('DO', 'Dominican Republic', 164) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('EC', 'Ecuador', 165) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('EG', 'Egypt', 166) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SV', 'El Salvador', 167) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GQ', 'Equatorial Guinea', 168) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('ER', 'Eritrea', 169) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('EE', 'Estonia', 170) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SZ', 'Eswatini', 171) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('ET', 'Ethiopia', 172) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('FK', 'Falkland Islands', 173) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('FO', 'Faroe Islands', 174) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('FJ', 'Fiji', 175) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('FI', 'Finland', 176) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('FR', 'France', 177) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GF', 'French Guiana', 178) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('PF', 'French Polynesia', 179) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TF', 'French Southern Territories', 180) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GA', 'Gabon', 181) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GM', 'Gambia', 182) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GE', 'Georgia', 183) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('DE', 'Germany', 184) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GH', 'Ghana', 2) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GI', 'Gibraltar', 186) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GR', 'Greece', 187) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GL', 'Greenland', 188) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GD', 'Grenada', 189) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GP', 'Guadeloupe', 190) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GU', 'Guam', 191) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GT', 'Guatemala', 192) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GG', 'Guernsey', 193) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GN', 'Guinea', 194) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GW', 'Guinea-Bissau', 195) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GY', 'Guyana', 196) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('HT', 'Haiti', 197) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('HM', 'Heard Island and McDonald Islands', 198) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('VA', 'Holy See', 199) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('HN', 'Honduras', 200) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('HK', 'Hong Kong', 201) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('HU', 'Hungary', 202) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('IS', 'Iceland', 203) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('IN', 'India', 204) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('ID', 'Indonesia', 205) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('IR', 'Iran', 206) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('IQ', 'Iraq', 207) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('IE', 'Ireland', 208) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('IM', 'Isle of Man', 209) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('IL', 'Israel', 210) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('IT', 'Italy', 211) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('JM', 'Jamaica', 212) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('JP', 'Japan', 213) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('JE', 'Jersey', 214) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('JO', 'Jordan', 215) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('KZ', 'Kazakhstan', 216) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('KE', 'Kenya', 3) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('KI', 'Kiribati', 218) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('KP', 'Korea, Democratic People''s Republic of', 219) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('KR', 'Korea, Republic of', 220) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('KW', 'Kuwait', 221) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('KG', 'Kyrgyzstan', 222) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('LA', 'Lao People''s Democratic Republic', 223) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('LV', 'Latvia', 224) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('LB', 'Lebanon', 225) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('LS', 'Lesotho', 226) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('LR', 'Liberia', 227) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('LY', 'Libya', 228) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('LI', 'Liechtenstein', 229) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('LT', 'Lithuania', 230) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('LU', 'Luxembourg', 231) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MO', 'Macao', 232) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MG', 'Madagascar', 233) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MW', 'Malawi', 234) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MY', 'Malaysia', 235) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MV', 'Maldives', 236) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('ML', 'Mali', 237) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MT', 'Malta', 238) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MH', 'Marshall Islands', 239) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MQ', 'Martinique', 240) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MR', 'Mauritania', 241) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MU', 'Mauritius', 242) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('YT', 'Mayotte', 243) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MX', 'Mexico', 244) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('FM', 'Micronesia', 245) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MD', 'Moldova', 246) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MC', 'Monaco', 247) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MN', 'Mongolia', 248) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('ME', 'Montenegro', 249) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MS', 'Montserrat', 250) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MA', 'Morocco', 251) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MZ', 'Mozambique', 252) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MM', 'Myanmar', 253) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('NA', 'Namibia', 254) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('NR', 'Nauru', 255) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('NP', 'Nepal', 256) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('NL', 'Netherlands', 257) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('NC', 'New Caledonia', 258) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('NZ', 'New Zealand', 259) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('NI', 'Nicaragua', 260) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('NE', 'Niger', 261) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('NG', 'Nigeria', 1) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('NU', 'Niue', 263) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('NF', 'Norfolk Island', 264) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MK', 'North Macedonia', 265) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MP', 'Northern Mariana Islands', 266) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('NO', 'Norway', 267) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('OM', 'Oman', 268) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('PK', 'Pakistan', 269) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('PW', 'Palau', 270) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('PS', 'Palestine, State of', 271) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('PA', 'Panama', 272) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('PG', 'Papua New Guinea', 273) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('PY', 'Paraguay', 274) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('PE', 'Peru', 275) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('PH', 'Philippines', 276) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('PN', 'Pitcairn', 277) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('PL', 'Poland', 278) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('PT', 'Portugal', 279) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('PR', 'Puerto Rico', 280) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('QA', 'Qatar', 281) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('RE', 'Réunion', 282) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('RO', 'Romania', 283) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('RU', 'Russian Federation', 284) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('RW', 'Rwanda', 285) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('BL', 'Saint Barthélemy', 286) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 287) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('KN', 'Saint Kitts and Nevis', 288) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('LC', 'Saint Lucia', 289) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('MF', 'Saint Martin', 290) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('PM', 'Saint Pierre and Miquelon', 291) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('VC', 'Saint Vincent and the Grenadines', 292) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('WS', 'Samoa', 293) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SM', 'San Marino', 294) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('ST', 'Sao Tome and Principe', 295) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SA', 'Saudi Arabia', 296) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SN', 'Senegal', 297) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('RS', 'Serbia', 298) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SC', 'Seychelles', 299) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SL', 'Sierra Leone', 300) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SG', 'Singapore', 301) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SX', 'Sint Maarten', 302) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SK', 'Slovakia', 303) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SI', 'Slovenia', 304) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SB', 'Solomon Islands', 305) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SO', 'Somalia', 306) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('ZA', 'South Africa', 4) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GS', 'South Georgia and the South Sandwich Islands', 308) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SS', 'South Sudan', 309) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('ES', 'Spain', 310) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('LK', 'Sri Lanka', 311) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SD', 'Sudan', 312) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SR', 'Suriname', 313) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SJ', 'Svalbard and Jan Mayen', 314) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SE', 'Sweden', 315) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('CH', 'Switzerland', 316) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('SY', 'Syrian Arab Republic', 317) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TW', 'Taiwan', 318) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TJ', 'Tajikistan', 319) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TZ', 'Tanzania', 320) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TH', 'Thailand', 321) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TL', 'Timor-Leste', 322) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TG', 'Togo', 323) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TK', 'Tokelau', 324) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TO', 'Tonga', 325) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TT', 'Trinidad and Tobago', 326) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TN', 'Tunisia', 327) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TR', 'Türkiye', 328) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TM', 'Turkmenistan', 329) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TC', 'Turks and Caicos Islands', 330) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('TV', 'Tuvalu', 331) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('UG', 'Uganda', 332) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('UA', 'Ukraine', 333) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('AE', 'United Arab Emirates', 334) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('GB', 'United Kingdom', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('US', 'United States', 6) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('UM', 'United States Minor Outlying Islands', 337) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('UY', 'Uruguay', 338) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('UZ', 'Uzbekistan', 339) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('VU', 'Vanuatu', 340) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('VE', 'Venezuela', 341) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('VN', 'Viet Nam', 342) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('VG', 'Virgin Islands, British', 343) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('VI', 'Virgin Islands, U.S.', 344) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('WF', 'Wallis and Futuna', 345) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('EH', 'Western Sahara', 346) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('YE', 'Yemen', 347) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('ZM', 'Zambia', 348) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;
INSERT INTO community_countries (code, name, sort_order) VALUES ('ZW', 'Zimbabwe', 349) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order, is_enabled = TRUE;

ALTER TABLE users ADD COLUMN IF NOT EXISTS country_code VARCHAR(8);
